services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - '6379:6379'

  poller-service:
    build:
      context: ./services/poller-service
    container_name: poller-service
    depends_on:
      - kafka
    volumes:
      - ./services/poller-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./services/poller-service/.env

  consumer-service:
    build:
      context: ./services/consumer-service
    container_name: consumer-service
    depends_on:
      - kafka
      - redis
    volumes:
      - ./services/consumer-service:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./services/consumer-service/.env